import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientCookiesProvider from "@/components/client-cookies-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col px-8`}
      >
        <ClientCookiesProvider>
        {children}
        </ClientCookiesProvider>
      </body>
    </html>
  );
}
